name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.ranull.graves.Graves
api-version: 1.13
authors:
  - Ranull
  - JaySmethers
  - Legoman99573
load: POSTWORLD
website: https://www.spigotmc.org/resources/gravesx.118271/

loadbefore:
  - XItemsRemover
  - ExplodeAny

softdepend:
  - Vault
  - ProtocolLib
  - WorldEdit
  - WorldGuard
  - GriefDefender
  - GriefPrevention
  - PlaceholderAPI
  - FurnitureLib
  - FurnitureEngine
  - ProtectionLib
  - MineDownPlugin
  - ChestSort
  - ItemsAdder
  - Oraxen
  - ProtocolLib
  - SkullTextureAPI
  - ItemBridge
  - PlayerNPC
  - Skript
  - Citizens
  - FancyNpcs
  - floodgate
  - Towny
  - LuckPerms
  - CoreProtect
  - NBTAPI

commands:
  graves:
    description: Graves command
    default: true
    usage: /graves
    aliases:
      - grave
      - gravesx
      - tombstones
      - tombstone
      - deathchests
      - deathchest
      - deaths
      - death
      - tombs
      - tomb
      - dc
      - d

  graveyards:
    description: Graveyards command
    default: true
    usage: /graveyards
    aliases:
      - graveyard
      - cemeteries
      - cemetery
      - burialgrounds
      - burialground
      - churchyards
      - churchyard
      - necropolises
      - necropolis
      - gy
      - g

permissions:
  graves.place:
    default: true
    description: Can place a graves

  graves.open:
    default: true
    description: Can open a grave

  graves.autoloot:
    default: true
    description: Can Autoloot a grave

  graves.break:
    default: true
    description: Can break a grave

  graves.gui:
    default: true
    description: Can view graves

  graves.potion-effect:
    default: true
    description: Can receive potion effect on respawn

  graves.gui.other:
    default: op
    description: Can view other peoples graves

  graves.experience:
    default: true
    description: Can store experience in graves

  graves.protection:
    default: true
    description: Can have protection on graves

  graves.teleport:
    default: true
    description: Can teleport to grave

  graves.teleport.bypass:
    default: op
    description: Bypass cost to teleport to others graves

  graves.teleport.delay-bypass:
    default: op
    description: Allows the player to bypass grave teleport delay restrictions

  graves.teleport.world.*:
    default: true
    description: Allows teleportation to graves in specific worlds.

  graves.bypass:
    default: op
    description: Bypass grave protection and cost to teleport to others graves

  graves.dump:
    default: op
    description: Dump server information

  graves.max.replace:
    default: true
    description: Replaces the oldest grave

  graves.max.limit.*:
    default: false
    description: Sets the max amount of graves a player has. Falls back to the max grave limit in grave.yml

  graves.max.bypass:
    default: op
    description: Allows players to bypass to the max grave limit in grave.yml

  graves.purge:
    default: op
    description: Purge graves

  graves.cleanup:
    default: op
    description: Cleanup graves

  graves.debug:
    default: op
    description: Change debug level

  graves.update.notify:
    default: op
    description: Notify player about plugin update

  graves.import:
    default: op
    description: Import graves from another plugin

  graves.givetoken:
    default: op
    description: Give a grave token

  graves.graveyard:
    default: true
    description: Graveyard menu

  graves.graveyardadmin:
    default: op
    description: Graveyard creation/removal command

  graves.reload:
    default: op
    description: Reload Graves